---
- name: Install basic infrastructure for all the projects
  hosts: digital-ocean
  user: root
  tasks:
    - name: setting up the folder
      command: mkdir -p /root/deployments/hacienda.io.content-service

    - name: setting up the folder
      command: mkdir -p /root/archives

    - name: uploading tarball with the project
      copy: src=../build/hacienda.io.content-service.tar.gz dest=/root/archives/hacienda.io.content-service.tar.gz

    - name: untaring the project
      command: tar -xvf /root/archives/hacienda.io.content-service.tar.gz -C /root/deployments/hacienda.io.content-service

    - name: getting the gems (maybe i should not be doing this in prod)
      command: bundle install
      args:
        chdir: /root/deployments/hacienda.io.content-service

    - name: uploading service conf
      copy: src=files/hacienda.io.content-service.conf dest=/etc/init/hacienda.io.content-service.conf

    - name: restarting the unicorn service
      service: name=hacienda.io.content-service state=restarted

    - name: uploading nginx conf
      copy: src=files/app_nginx.conf dest=/etc/nginx/sites-available/hacienda.io.content-service.conf

    - name: uploading nginx conf
      copy: src=files/app_nginx.conf dest=/etc/nginx/sites-enabled/hacienda.io.content-service.conf

    - name: restarting the nginx service
      service: name=nginx state=restarted
