production:
  logging: true
  log_path: /tmp/content_service_dev.log
  content_directory_path: <path-to>/hacienda.io.content-service
  key_file: /tmp/content_service/keys_test.yml
  content_repo: hacienda.io.content
  github_user: tw-content-service
  github_organisation: www-thoughtworks-com

development:
  logging: true
  log_path: /tmp/content_service_dev.log
  content_directory_path: /tmp/development.content
  key_file: /tmp/content_service/keys_test.yml
  content_repo: hacienda.development.content
  github_user: tw-content-service